### ISSUE TITLE
can't get lilv instance

### ISSUE THREAD

**Issue by MaxPayne86** [brummer10/GxTubeDistortion.lv2#1]
1) It seems modgui.ttl has been deleted into MOD folder, but is referenced by manifest.ttl
2) Trying to use the old modgui.ttl file deleted in this repo, I get an error from jack module
mod-host: can't get lilv instance

I think it's only a matter of wrong names in the *.ttl files, but if nobody ask you will never know. Hope to help :)

**Comment by brummer10** [comment]
Hi
Thanks for the pointer. 
Indeed, didn't notice that I accidentally have deleted modgui.ttl. I also didn't have my old build folder any more. 
But I just checked my MOD and found the modgui.ttl file unchanged like the deleted one. 
So it should work with the old modgui.ttl file.
What differ is the gx_TubeDistortion.ttl, were the part 
```
<http://guitarix.sourceforge.net/plugins/gx_TubeDistortion_gui#_TubeDistortion_>
  a guiext:GtkUI;
  guiext:binary <gx_TubeDistortion_ui.so>;
  guiext:requiredFeature guiext:makeResident;
  .
```
needs to be deleted. 

Additional I've this part below the lv2:microVersion 0;
```

    mod:brand "Guitarix" ;
    mod:label "GxTubeDist" ;

```

but as far I know that isn't needed. 
You may want to try it with the edited gx_TubeDistortion.ttl, let my know if that work, otherwise I need to setup my build environment and check what happens. 

regards
hemrann

**Comment by MaxPayne86** [comment]
Hi,

I've just checked and it doesn't work, jack returns the same error. I don't know how you can have this effect in your Mod-Duo since it's not mentioned into the mod-plugin-builder. Anyway, I've tested GxLiquidDrive is working without problems and doesn't have

`mod:brand "Guitarix" ;`
`mod:label "GxTubeDist" ;`

**Comment by brummer10** [comment]
Okay, so I've setup my build environment and rebuild GxTubeDistortion, and pushed it to my MOD. It's working here (after fix the issue). I've pushed the fix to the git repository now. 

well, I didn't forward any of my plugs to the MOD. GxTubeDistortion, for example, use to much CPU on the MOD, as it works on 96kHz so need upsampling. That's why I didn't forward it to the mod-plugin-builder. There are a lot other plugs which work much better on the MOD. 

I hope the fix work for you as well now.

regards
hermann

**Comment by MaxPayne86** [comment]
> Okay, so I've setup my build environment and rebuild GxTubeDistortion, and pushed it to my MOD. It's working here (after fix the issue). I've pushed the fix to the git repository now.
> 
> well, I didn't forward any of my plugs to the MOD. GxTubeDistortion, for example, use to much CPU on the MOD, as it works on 96kHz so need upsampling. That's why I didn't forward it to the mod-plugin-builder. There are a lot other plugs which work much better on the MOD.
> 
> I hope the fix work for you as well now.
> 
> regards
> hermann

I've tested it and it works, to be honest was probably working with the fix proposed by you but I forgot to restart everything and do a restart of mod-ui only.
Regarding CPU consumption on my board I have 14-15% CPU so should be ok for me.

Thanks,
